# Generated by Django 5.0.1 on 2024-07-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techbeatricepostmodel',
            name='techbeatrice_cost_price',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AddField(
            model_name='techbeatricepostmodel',
            name='techbeatrice_img',
            field=models.ImageField(blank=True, null=True, upload_to='tech_images/'),
        ),
    ]
