# Generated by Django 5.0.1 on 2024-07-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0002_techbeatricepostmodel_techbeatrice_cost_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techbeatricepostmodel',
            options={'ordering': ['-techbeatrice_courses_publish_date']},
        ),
        migrations.RenameField(
            model_name='techbeatricepostmodel',
            old_name='techbeatrice_author',
            new_name='techbeatrice_courses_author',
        ),
        migrations.RenameField(
            model_name='techbeatricepostmodel',
            old_name='techbeatrice_cost_price',
            new_name='techbeatrice_courses_cost_price',
        ),
        migrations.RenameField(
            model_name='techbeatricepostmodel',
            old_name='techbeatrice_description',
            new_name='techbeatrice_courses_description',
        ),
        migrations.RenameField(
            model_name='techbeatricepostmodel',
            old_name='techbeatrice_img',
            new_name='techbeatrice_courses_img',
        ),
        migrations.RenameField(
            model_name='techbeatricepostmodel',
            old_name='techbeatrice_publish_date',
            new_name='techbeatrice_courses_publish_date',
        ),
        migrations.RenameField(
            model_name='techbeatricepostmodel',
            old_name='techbeatrice_slug',
            new_name='techbeatrice_courses_slug',
        ),
        migrations.RenameField(
            model_name='techbeatricepostmodel',
            old_name='techbeatrice_title',
            new_name='techbeatrice_courses_title',
        ),
    ]
