# Generated by Django 5.0.1 on 2024-07-14 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0003_alter_techbeatricepostmodel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechbeatricePostModel',
            new_name='Techbeatrice_Courses_PostModel',
        ),
    ]
