# Generated by Django 5.0.1 on 2024-07-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0005_alter_techbeatrice_courses_postmodel_techbeatrice_courses_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techbeatrice_courses_postmodel',
            name='techbeatrice_courses_sub_img',
            field=models.ImageField(blank=True, null=True, upload_to='tech_courses_sub_img/'),
        ),
        migrations.AddField(
            model_name='techbeatrice_subjects',
            name='techbeatrice_subjects_sub_img',
            field=models.ImageField(blank=True, null=True, upload_to='tech_subjects_sub_img/'),
        ),
    ]
