# Generated by Django 5.0.1 on 2024-07-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0006_techbeatrice_courses_postmodel_techbeatrice_courses_sub_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techbeatrice_courses_postmodel',
            name='techbeatrice_courses_sub_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techbeatrice_courses_postmodel',
            name='techbeatrice_courses_sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='techbeatrice_subjects',
            name='techbeatrice_subjects_sub_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techbeatrice_subjects',
            name='techbeatrice_subjects_sub_title',
            field=models.CharField(blank=True, max_length=205, null=True),
        ),
    ]
