# Generated by Django 5.0.1 on 2024-07-22 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0007_techbeatrice_courses_postmodel_techbeatrice_courses_sub_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Techbeatrice_Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techbeatrice_instructor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('techbeatrice_instructor_description', models.TextField()),
                ('techbeatrice_instructor_img', models.ImageField(blank=True, null=True, upload_to='instructor_img/')),
                ('techbeatrice_instructor_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('techbeatrice_instructor_publish_date', models.DateTimeField(auto_now_add=True)),
                ('techbeatrice_instructor_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-techbeatrice_instructor_publish_date'],
            },
        ),
    ]
