# Generated by Django 5.0.1 on 2024-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0008_techbeatrice_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='techbeatrice_instructor',
            name='techbeatrice_instructor_position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
