# Generated by Django 5.0.1 on 2024-07-28 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0010_techbeatrice_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_title', models.CharField(blank=True, max_length=255, null=True)),
                ('courses_description', models.TextField()),
                ('courses_position', models.CharField(blank=True, max_length=255, null=True)),
                ('courses_img', models.ImageField(blank=True, null=True, upload_to='courses_img/')),
                ('courses_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('courses_publish_date', models.DateTimeField(auto_now_add=True)),
                ('courses_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-courses_publish_date'],
            },
        ),
        migrations.DeleteModel(
            name='Techbeatrice_Courses',
        ),
    ]
