# Generated by Django 5.0.1 on 2024-07-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0011_courses_delete_techbeatrice_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='courses_position',
        ),
    ]
