# Generated by Django 5.0.1 on 2024-08-10 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0013_under_enroll'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Techbeatrice_first_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techbeatrice_first_img_title', models.CharField(blank=True, max_length=205, null=True)),
                ('techbeatrice_first_img_description', models.TextField()),
                ('techbeatrice_first_img_slug', models.CharField(blank=True, max_length=205, null=True)),
                ('techbeatrice_first_img_publish_date', models.DateTimeField(auto_now_add=True)),
                ('techbeatrice_first_img_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-techbeatrice_first_img_publish_date'],
            },
        ),
    ]
