# Generated by Django 5.0.1 on 2024-08-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0014_techbeatrice_first_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='techbeatrice_first_img',
            name='techbeatrice_subjects_img',
            field=models.ImageField(blank=True, null=True, upload_to='tech_first_img/'),
        ),
    ]
