# Generated by Django 5.0.1 on 2024-08-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techbeatrice', '0015_techbeatrice_first_img_techbeatrice_subjects_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='techbeatrice_first_img',
            old_name='techbeatrice_subjects_img',
            new_name='techbeatrice_first_img_img',
        ),
    ]
